//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieList.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Movies
    {
        public int ID { get; set; }
        public string Title { get; set; }
        [DisplayName("Release Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy}")]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> GenreID { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
